log: /tmp/oregpt/
openai:
    model: gpt-3.5-turbo
# You can also specify OpenAI's API key here
#     api_key: <your-api-key>
character:
    assistant:
        name: AI
        style: "#87CEEB"
        role: "You are a chat bot"
    user:
        name: Me
        style: "#00BEFE"
    system:
        name: System
        style: "#cc0000"
